# Generated by Django 3.2.12 on 2022-03-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('team', models.CharField(max_length=128, verbose_name='Team/Country')),
                ('noc', models.CharField(max_length=3, verbose_name='National Olympic Committee')),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Event')),
                ('sport', models.CharField(max_length=256, verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Game name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=64, verbose_name='Season')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('events', models.ManyToManyField(blank=True, related_name='games', to='olympics.Event', verbose_name='Events')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('NA', 'No medal')], max_length=16, verbose_name='Medal')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympics.athlete', verbose_name='Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympics.event', verbose_name='Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympics.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Medal',
                'verbose_name_plural': 'Medals',
                'ordering': ['game'],
            },
        ),
    ]
