# Generated by Django 3.2.12 on 2022-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='medal',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('0', 'No medal'), ('NA', 'No medal')], max_length=16, verbose_name='Medal'),
        ),
    ]
