# Generated by Django 3.2.12 on 2022-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0004_alter_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='medal',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Medal'),
        ),
    ]
