# Generated by Django 3.2.12 on 2022-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0005_alter_medal_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='medal',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('0', 'No medal'), ('NA', 'No medal')], max_length=16, null=True, verbose_name='Medal'),
        ),
    ]
