version: '3.7'

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - DEFAULT_MYSQL_PASS=mysql

  django:
    environment:
      - DATABASE=${DEVELOP_DJANGO_DATABASE}
      - SQL_ENGINE=${DEVELOP_SQL_ENGINE}
      - SQL_DATABASE=${DEVELOP_DJANGO_DATABASE}
      - SQL_USER=${DEVELOP_POSTGRES_USER}
      - SQL_PASSWORD=${DEVELOP_POSTGRES_PASSWORD}
      - SQL_HOST=${DEVELOP_SQL_HOST}
      - SQL_PORT=${DEVELOP_SQL_PORT}
      - MODE=${DEVELOP_MODE}
      - FIXTURE=${DEVELOP_FIXTURE}
      - DJANGO_SUPERUSER_USERNAME=${DEVELOP_DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DEVELOP_DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DEVELOP_DJANGO_SUPERUSER_EMAIL}

  postgres:
    environment:
      - DATABASE=${DEVELOP_DJANGO_DATABASE}
      - SQL_DATABASE=${DEVELOP_DJANGO_DATABASE}
      - SQL_USER=${DEVELOP_POSTGRES_USER}
      - SQL_PASSWORD=${DEVELOP_POSTGRES_PASSWORD}
      - SQL_HOST=${DEVELOP_SQL_HOST}
      - SQL_PORT=${DEVELOP_SQL_PORT}
